name: Android CI

defaults:
  run:
    shell: bash
    working-directory: engineering

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: engineering/app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"
    - name: Build Changelog
      uses: mikepenz/release-changelog-builder-action@v2.9.0
      id: build_changelog
      with:
        configuration: 'configuration.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - id: changelog
    #   uses: gandarez/changelog-action@v1.0.4
    # - name: Generate changelog
    #   id: changelog
    #   uses: metcalfc/changelog-generator@v3.0.0
    #   with:
    #     myToken: ${{ secrets.GITHUB_TOKEN }}
    - name: Print Changelog to file
      run: echo "${{ steps.build_changelog.outputs.changelog }}" | tee app/build/outputs/release-notes.txt

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: internal 
        # releaseNotes: "${{steps.changelog.outputs.changelog}}"
        releaseNotesFile: engineering/app/build/outputs/release-notes.txt
        # file: engineering/app/build/outputs/apk/debug/app-debug.apk
        file: engineering/app/build/outputs/apk/release/app-release-signed.apk
#        file: engineering/app/build/outputs/apk/release/app-release-unsigned.apk
